{"name": "Validate the Git API", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\Umesh_Kumar\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Umesh_Kumar\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\stepsAddBooksFunctionality.py\", line 43, in step_impl\n    assert context.response.status_code == statusCode\n"}, "steps": [{"name": "Given I have the github Auth cedentails", "status": "passed", "start": 1638840350170, "stop": 1638840350172}, {"name": "When I hit the gitRep API of GITHUB", "status": "passed", "start": 1638840350172, "stop": 1638840350902}, {"name": "Then status code of response should be 200", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\Umesh_Kumar\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Umesh_Kumar\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\stepsAddBooksFunctionality.py\", line 43, in step_impl\n    assert context.response.status_code == statusCode\n"}, "start": 1638840350902, "stop": 1638840350905}], "start": 1638840350168, "stop": 1638840350906, "uuid": "f16822b1-55b8-4493-a3c0-cf890ed1bfe3", "historyId": "da13230b3b4df81c655091d305228e2b", "fullName": "# Enter feature name here: Validate the Git API", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# Enter feature name here"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}